apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Michela877/testdockerimage.git
    targetRevision: argocd
    path: argocd-apps          # qui punta alla cartella che contiene tutte le Application figlie
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
