apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: flask-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask
        image: test.local/michela877/flask-hello:@sha256:68aafa565bbb4488616cc8cefe3e2b3ba21dd469d7d81ad3c0c6ab48a5cccbfe  # SENZA TAG
        ports:
        - containerPort: 8081
        env:
        - name: FLASK_ENV
          value: "production"
