apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask-hello
resources:
  - deployment.yaml
  - service.yaml

# Questa è la parte importante per Image Updater
images:
  - name: test.local/michela877/flask-hello
    newTag: 1.0v
